version: '3.8'

services:

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: cv_db
    ports:
      - '5432:5432'

