def root_error_formater(errors: list[dict[str, str]]) -> dict[str, list[str]]:
    """
    Formats root error messages to unify errors format
    """
    error_msg = errors[0]["msg"].split(": ")
    return {error_msg[0]: [error_msg[1]]}


def format_error_msg(errors: list[dict[str, str]]) -> dict[str, list[str]]:
    """
    Modifies strings generated by validation error to dict
    """
    if "__root__" in errors[0]["loc"]:
        return root_error_formater(errors)

    formatted_msg = {}
    for error in errors:
        if len(error["loc"]) == 1:
            formatted_msg[error["loc"][-1]] = error["msg"].split(", ")
        elif len(error["loc"]) > 1:
            formatted_msg[f"{error['loc'][-2]}: {error['loc'][-1]}"] = error[
                "msg"
            ].split(", ")

    return formatted_msg
